spring.application.name=sistema-de-login-seguro

# Conexão segura ao MongoDB Atlas utilizando variável de ambiente MONGODB_URI.
# Caso a variável não esteja definida, utiliza a conexão local como fallback.
spring.mongodb.uri=mongodb://localhost:27017
spring.mongodb.database=sistema

spring.main.allow-bean-definition-overriding=true

# Configurações do Thymeleaf (desativa a cache em desenvolvimento)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8